baseURL = "https://bardenn.uk/"
theme = "retro"
languageCode = "en"
title = "bardenn's blog"
copyright = "© bardenn CC BY-SA 4.0"


enableRobotsTXT = true
enableEmoji = true
capitalizeListTitles = false

disableKinds = ["taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorfilename/"
tags = "/blog/:slug"

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "baz's blog"
description = "Personal blog, Compsci, hackery and Randomposting"
favicon = "img/favicon.png"
icon = "img/icon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = true
webbadge = "/img/bardenn.gif"

[params.author]
name = "Hussein Dennis"
email = "bardennuk@gmail.com"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menu.main]]
name = "Blog"
pageRef = "/blog"
weight = 20

[[menu.main]]
name = "linkdex"
url = "/linkdex"
weight = 30

[[menu.main]]
name = "friends"
url = "/friends"
weight = 30


[[menu.main]]
name = "RSS"
url = "/index.xml"
weight = 40

[services.rss]
limit = 50

[outputs]
section = ["html"]
taxonomy = ["html"]
term = ["html"]