name = 'retro'
license = 'MIT'
licenselink = 'LICENSE'
description = 'Local retro theme for bardenn.github.io'

# The home page of the theme, where the source can be found
homepage = 'https://bardenn.uk/'

# Taxonomy terms
tags = ['blog', 'retro']
features = ['blog', 'rss', 'font selector']

# If the theme has a single author
[author]
  name = 'Hussein Dennis'
  homepage = 'https://bardenn.uk/'
